### ISSUE TITLE
I NEED HELP sorry I can not type this in the comment when I press the put-on button my finger goes right inside it, and nothing happens

### ISSUE THREAD

**Issue by jackbo33** [GreenMan36/AllGorillaTagHats#6]
HI my gorilla tag cosmetics mod is not working specifically the hats. is there a way to fix it.

**Comment by GreenMan36** [comment]
Sorry but this project has been stale for a while, all this GIT is is a collection of other's work.
I don't make mods, or maintain any so I can't help you.

For support you should go to the [Gorilla Tag Modding discord](https://discord.gg/monkemod).

**Comment by jackbo33** [comment]
thank you
